// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWfrzq_7zrBIERX0jEt0cAGl08wehev08',
    appId: '1:146673778766:web:723211f92cb61fbe75031f',
    messagingSenderId: '146673778766',
    projectId: 'cookify-a91dd',
    authDomain: 'cookify-a91dd.firebaseapp.com',
    storageBucket: 'cookify-a91dd.firebasestorage.app',
    measurementId: 'G-C9823EYN24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlqAd3aDHgI9ITOHlMd8Xcw6f7sCy9ZNQ',
    appId: '1:146673778766:android:2f0c475be27bb42f75031f',
    messagingSenderId: '146673778766',
    projectId: 'cookify-a91dd',
    storageBucket: 'cookify-a91dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChXRNGLtjPaUWf-ub7bJNCZaYV_HKjwpI',
    appId: '1:146673778766:ios:c0ac36bb7c5315ef75031f',
    messagingSenderId: '146673778766',
    projectId: 'cookify-a91dd',
    storageBucket: 'cookify-a91dd.firebasestorage.app',
    iosBundleId: 'com.example.cookify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWfrzq_7zrBIERX0jEt0cAGl08wehev08',
    appId: '1:146673778766:web:16b61df6eb671a8275031f',
    messagingSenderId: '146673778766',
    projectId: 'cookify-a91dd',
    authDomain: 'cookify-a91dd.firebaseapp.com',
    storageBucket: 'cookify-a91dd.firebasestorage.app',
    measurementId: 'G-JGX2SBCR8D',
  );

}